//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _301_EFProjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_1
    {
        public int LocationId { get; set; }
        public string LocationCity { get; set; }
        public string LocationCountry { get; set; }
        public Nullable<byte> LocationCapacity { get; set; }
        public Nullable<decimal> LocationPrica { get; set; }
        public string Daynight { get; set; }
    }
}
